{% set name = "sklearn-contrib-lightning" %}
{% set version = "0.6.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/scikit-learn-contrib/lightning.git
  git_rev: f05855f4ef9e7415c9afd16a033f2d2a4c192848
  patches:
    - fix_tests.patch 

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
  host:
    - python
    - pip
    - setuptools
    - numpy 
    - cython
    - scikit-learn
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scikit-learn

test:
  requires:
    - numpy
    - scikit-learn
    - nose
  imports:
    - lightning

about:
  home: http://contrib.scikit-learn.org/lightning/
  license: BSD 3-Clause
  summary: lightning is a library for large-scale linear classification, regression and ranking in Python.
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - fabianp
    - mblondel
