{% set name = "sklearn-contrib-lightning" %}
{% set version = "0.6.0" %}
{% set hash_val = "fe7ea12831425cb1feaef072542e21dd" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  md5: {{ hash_val }}
  patches:
    - fix_tests.patch 

build:
  number: 0
  skip: True  # [py2k]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
  host:
    - python
    - pip
    - setuptools
    - numpy 
    - cython
    - scikit-learn
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scikit-learn

test:
  requires:
    - numpy
    - scikit-learn
    - nose
  imports:
    - lightning

about:
  home: http://contrib.scikit-learn.org/lightning/
  license: BSD 3-Clause
  summary: lightning is a library for large-scale linear classification, regression and ranking in Python.
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - fabianp
    - mblondel
