travis:
  secure:
    BINSTAR_TOKEN: TXp3ypqH+Tiq7rE2wJPowtXcrosAujFylujr9A31IQGIgvBo3MaAGBmFUa0qRSgRN5WzW4CnCpRV/9K+DMVmGDBfxiA+Zta3HrQJ8mmwcZruiazgnFKEWOOEbqtTz82ssYlJTGJ+Gr5FL05yJcLw/P6aujIKdS2XeqbjjZ3JNJTD8WXoFmdr+A/lIJk22rK7kau3vc2k8YuIp7rDfwcI31C/TVyOBfbtfkvdFAtNZp82M+Hzk7uggA9+Ehh5UW9bX8SrnG1nDDMXXSsGssF50xHcFKzX8WrkDAZkm9URDvgTDbpAD/wPHrQnvcZo0/ytEXXQkcld2glLHxA6zxb0eHWssc3uMOuXDfnWDAPKpxN59Ac4eN+H0Wg8wojuK2h0hS6goVvOy8sK1f3eo/ssHZSL7EgN16rgHG1BjQm9jbrIMgpYrq9W47zyxJ6fV9VZlLFjKHH3Xgwc1arK2/Q0DmlbxWlQLlWvxWi7UCvhcMa1mV41ZCdrhfDw4/gx2VcnmPnZl0R8Xia91+W3LKJyuXi8n0lwzvsrXUDUz/InWDvaKJRrB4lDtLi31LSLyIm1U6pK//lHTedoKe5twJb77LMZayH4jb9iDjKu4aIh9F+zl3EAvuaCertkH39CPl1z8QFSN5rLbeKLJA1iw+Ji6SPHjXtecwTacNGX52q1a3A=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
