travis:
  secure:
    BINSTAR_TOKEN: R4A9fdJJTktwv7jR/EZI1FadCPNJE00N+xZPbNJ2FeVqsE+c5gi4GWZNgYCQ4Yi6dcBqIpUHMBZuybv46A4XaVQjmjePRYYXkddINX8+4Vc4d10OPY0BMs29dCCNcdFJh0FsTIUVu7KYG5lumv/ymhHdv7j7is4Lxyww0uBNsTei/fd6GB8a9I04aWJBXDij3aqaH9EcjtKUNJPb3Ji98CC0J4JJbC/nGl7UoSkDyk+FuJbyU2j+Bs3Y14X+V30rJjvXXYv4V1R5YRMcbaVkzIyejOAND5q+jTt7zFGj8xQbdbx/kaHe2vD1N2eKeF0iEIgEL1pqw4DiM8s7gDvwMVoyTONs5QMCFfwf7pPpojCTVQ8sKmDmaIeUvM+eHUNHYGsHoNyEVBM+EdVJNNUPZ5VgdJUNgskWOU8Pw0mdyNc7UjBgCY6dCMSPuIdkmtUIts5m5mFi4/KahWTQRFOSdS2XZGIo9PXf3rqqhhn7YcBIxj+4XvrvwQzvY8NxrwZaLiSne/yUfAHLF5qazyMGOagsIvpBjIpqQUwqvdp8VS/GmkseHEEdSGdBZYwaXVTDMOJUHftbL+EJOvx852fsoBLgY5KyLanGUQ1xAupHdcJeOy447TrNyDJBiQxg8VALdjxdwMX4dHEgBIHXTUU5ozHoi6nPQLTL89vbegnkOXc=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
