travis:
  secure:
    BINSTAR_TOKEN: mnW/jouQbSqfWgyruS7EgePGXmaptRPFmFI00eRfIgb7YDX7nPQnpjA7P5EM9V3Yiq6KxK1ImhHadUhRzDZqRVjHr2IQgzL/e7Ca1bevSYQ1UuJF7/utV5OAqnqar8wZPg37CXAISjtGV66CZte82TO01GfcJY9je7+VVHSdZvXO+SNdblrolDzCtqu7F3namGMHxer/vphoPq++ze71NcJokJufvp6CWZ/Dp80JkcQWgM+sidSrhpKxllQa+o2rn2myyagB1Y/uTrZ7lSwH9OtzEnmE3mQ1SUy4nOrTOfR/4mBEFG1s1cyP2fQ080T0Ih9xcp/BlXTo6mw5kCV4rfHIWsh7AtR/Q07w9KF4cd0ixx2OUPwmc+L8InLcgEhPBw1UZnAjEVPNsml8nPiELZFoKhbhYMEXkxmTCvJHxmP6LEgxQ0vuV7nHLzcVD1pFKejCECFyvtp2WwLNLIdQG/L8rEap7glTxeSmIUFZNz470osHLQoBSzlVxIzmuGIHNHljXh171FO6gjnF2kfEuxWloGtEkoJCe7Lt30gDDxlhbx91ZwgA9Lw0TArxZ5IcQbzOBG168tXtbf7e8KDOwDitMwfRyfNLEhyVOxTNHlFQJ9coEEqC3k/xMfLhoiNJXaUiAhrNHr6q9Rw2YnVP61uIIc3iqqx1yQsYblYzkRI=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
